Add oracle callback example
gelatodigital/web3-functions-hardhat-template pull request #8
Opened 2023-12-11 07:50 UTC by anirudhmakhana

- Add w3f to showcase oracle callback example
- onFail -> send slack alert or email
- userArgs.json -> define what type of alert you want on fail. Either slack email, or both.

2023-12-13 11:13 UTC, goums requested changes

2023-12-13 11:13 UTC, goums commented on web3-functions/oracle-callback slack/index.ts
> +import {
@anirudhmakhana please rename the dir, it's containing a space `oracle-callback slack` instead of a dash `oracle-callback-slack`

2023-12-13 11:17 UTC, goums requested changes

2023-12-13 11:17 UTC, goums commented on web3-functions/oracle-callback slack/index.ts
> +  const SLACK_WEBHOOK_URL = "YOUR_SLACK_WEBHOOK_URL";
webhook url should come from secrets or anyone will be able to exploit it

2023-12-13 11:17 UTC, goums commented on yarn.lock
> +"@gelatonetwork/web3-functions-sdk@2.2.0":
please update to 2.2.1 as it contains a callbacks fix

2023-12-14 07:06 UTC, donoso-eth approved these changes

2023-12-14 07:06 UTC, merged